import json

# Define 70 unique, realistic, authentic names for each of the 10 categories
categories_names = {
    "Strength": [
        "Calibrated Steel Competition Bumper Plate (45 lbs)",
        "Chrome Olympic Barbell (220K PSI Steel)",
        "Cast Iron Kettlebell (24kg / 53lbs)",
        "Rubber Coated Hex Dumbbell (30 lbs)",
        "Heavy-Duty Commercial Squat Rack",
        "Multi-Angle Adjustable Weight Bench",
        "Zinc-Coated Olympic Hex Trap Bar",
        "Urethane Pro Dumbbell Set (5-50 lbs)",
        "Steel Loadable Macebell (15 lbs)",
        "Wall-Mounted Heavy Foldable Power Rack",
        "Cast Iron Competition Kettlebell (16kg)",
        "Machined Steel Weight Plate (25 lbs)",
        "Stainless Steel Powerlifting Barbell",
        "Commercial Smith Machine Rack System",
        "Adjustable Incline Flat Decline Bench",
        "Solid Rubber Bumper Plate (10kg)",
        "Open Ended Trap Bar with Built-in Jack",
        "Rubber Hex Dumbbell Pair (40 lbs)",
        "Cast Iron Kettlebell (32kg / 70lbs)",
        "Half Rack Rig with Safety Spotter Arms",
        "Hard Chrome Olympic Training Bar (20kg)",
        "Urethane Coated Weight Plate (35 lbs)",
        "Heavy Duty Flat Utility Bench (1000lb Capacity)",
        "Powder Coated Cast Iron Kettlebell (12kg)",
        "Pro Style Steel Dumbbell Pair (25 lbs)",
        "Steel Cable Crossover Machine Tower",
        "Competition Bumper Plate Pair (20kg)",
        "Multi-Grip Curved Swiss Barbell",
        "Foldable Wall Rack with Pull-Up Bar",
        "Commercial Preacher Curl Bench",
        "Rubber Hex Dumbbell Pair (15 lbs)",
        "Cast Iron Kettlebell (20kg / 44lbs)",
        "Black Oxide Olympic Barbell (7 Foot)",
        "Steel Plate Loaded Lat Pulldown Machine",
        "Heavy Duty Ab Slab Incline Bench",
        "Calibrated Powerlifting Steel Plate (25kg)",
        "Steel Parallel Bars Dip Station",
        "Rubber Coated Hex Dumbbell (50 lbs)",
        "Ergonomic Handle Kettlebell (8kg)",
        "Commercial Leg Press Hack Squat Machine",
        "Cerakote Coated Olympic Barbell (Red/Black)",
        "Fractional Steel Change Plate Set (0.25kg - 5kg)",
        "Adjustable Speed Bench with Transport Wheels",
        "Cast Iron Kettlebell (28kg / 62lbs)",
        "Fixed Rubber Barbell Set (Straight Bar)",
        "Heavy Duty Plate Storage Tree Tower",
        "Multi-Grip Landmine Attachment for Barbells",
        "Commercial Cable Crossover Functional Trainer",
        "Rubber Hex Dumbbell Pair (35 lbs)",
        "Calibrated Competition Steel Plate (15kg)",
        "Hard Chrome EZ Curl Barbell (47 Inch)",
        "Commercial Glute Ham Developer (GHD) Machine",
        "Heavy Duty Adjustable Squat Stands Pair",
        "Cast Iron Kettlebell (14kg / 31lbs)",
        "Rubber Coated Hex Dumbbell (20 lbs)",
        "Commercial Functional Trainer Dual Pulley",
        "High-Tenacity Olympic Barbell Collar Clamp Pair",
        "Calibrated Bumper Plate Pair (10 lbs)",
        "Steel T-Bar Row Platform & Handle System",
        "Adjustable FID Bench (Flat Incline Decline)",
        "Cast Iron Competition Kettlebell (10kg)",
        "Rubber Hex Dumbbell Pair (45 lbs)",
        "Cerakote Women's Olympic Barbell (15kg)",
        "Plate Loaded Seated Calf Raise Machine",
        "Heavy Duty Power Rack Extension Conversion Kit",
        "Solid Steel Farmers Walk Handles Pair",
        "Rubber Coated Hex Dumbbell (60 lbs)",
        "Cast Iron Kettlebell (18kg / 40lbs)",
        "Steel Weight Plate Set (300lb Olympic Set)",
        "Heavy Duty Commercial Power Rack Cage"
    ],
    "Cardio": [
        "Commercial Motorized Treadmill with 15.6 Inch HD Touchscreen",
        "Air Resistance Rowing Machine with Performance Monitor",
        "Heavy-Duty Fan Blade Air Bike with LCD Console",
        "Magnetic Resistance Elliptical Cross Trainer",
        "Foldable Space-Saving Electric Treadmill",
        "Commercial Indoor Cycling Spin Bike with Magnetic Flywheel",
        "Stair Climber Stepper Machine with Ergonomic Handrails",
        "Self-Powered Curved Manual Treadmill",
        "Water Resistance Wood Rower with LCD Display",
        "Compact Under-Desk Walking Pad Treadmill",
        "Recumbent Exercise Bike with Padded Lumbar Support",
        "Commercial Grade Air Bike with Dual-Action Arms",
        "High-Intensity Interval Training Rower",
        "Smart Bluetooth Studio Spin Bike with Auto-Resistance",
        "Heavy-Duty Commercial Elliptical Trainer",
        "Compact Folding Magnetic Exercise Bike",
        "Commercial Stepper Mill Climber Machine",
        "Ultra-Quiet Magnetic Rowing Machine",
        "Heavy-Duty Treadmill with 3.5 HP Continuous Motor",
        "Air Resistance Cross Trainer Fitness Bike",
        "Foldable Walking Pad with Remote Control",
        "Professional Recumbent Stationary Bike",
        "Commercial Fluid Rower with Adjustable Resistance",
        "Smart Interactive Spin Bike with Tablet Holder",
        "Incline Trainer Treadmill with 0-40 Percent Incline",
        "Heavy Duty Fan Bike for Cross-Training",
        "Under-Desk Treadmill Walking Pad with LED Display",
        "Commercial Magnetic Elliptical Machine",
        "Dual-Handle Hydro Rowing Machine",
        "Upright Fitness Exercise Bike with Heart Rate Grips",
        "Smart Motorized Treadmill with Auto-Incline",
        "Full Body Air Rower with Smartphone Mount",
        "Magnetic Spin Bike with 40lb Flywheel",
        "Commercial Grade Stair Climber Stepper",
        "Compact Foldable Magnetic Rower",
        "Motorized Treadmill with Bluetooth Speakers",
        "High-Capacity Air Resistance Bike",
        "Desk Treadmill Under-Desk Walking Pad",
        "Recumbent Bike with Magnetic Resistance and LCD",
        "Water Rower Machine with Real Wood Frame",
        "Commercial Curved Manual Running Treadmill",
        "Indoor Studio Cycle Bike with Silent Belt Drive",
        "Heavy-Duty Elliptical Trainer with 20 Inch Stride",
        "Foldable Electric Treadmill with Cushioning System",
        "Air Resistance Rower with Wireless Heart Rate Receiver",
        "Heavy-Duty Fan Air Bike with Custom Workout Modes",
        "Stair Stepper Machine with Handlebars",
        "Magnetic Upright Exercise Bike with Tablet Stand",
        "Commercial Motorized Treadmill (4.0 HP Peak)",
        "Dual Resistance Air & Magnetic Rower",
        "Smart Indoor Spin Bike with Magnetic Resistance",
        "Portable Walking Pad Treadmill for Home Office",
        "Recumbent Exercise Bike with Quick-Adjust Seat",
        "Water Resistance Rower with Ergonomic Handle",
        "Heavy Duty Elliptical Cross Trainer with Power Incline",
        "Curved Manual Treadmill with Rubber Slat Belt",
        "Pro Studio Spin Bike with Dual SPD Pedals",
        "Compact Folding Motorized Treadmill",
        "Commercial Grade Air Rower with Steel Chain",
        "Heavy Duty Resistance Fan Bike",
        "Under-Desk Walking Pad Treadmill with Armrests",
        "Magnetic Elliptical Trainer with Heart Rate Sensors",
        "Wood Frame Hydro Rower Machine",
        "Upright Magnetic Fitness Bike",
        "Motorized Treadmill with Shock Absorption Deck",
        "Smart Air Rower with Bluetooth Connectivity",
        "Commercial Indoor Spin Bike with Heavy Flywheel",
        "Stair Climber Stepper with Multi-Grip Handles",
        "Foldable Space-Saving Magnetic Rower",
        "Commercial Heavy-Duty Motorized Treadmill"
    ],
    "Combat": [
        "Heavy Leather Punching Bag (100 lbs / 4ft)",
        "Pro Style Leather Boxing Headgear",
        "Elasticated Cotton Hand Wraps (180-Inch Pair)",
        "Pro Guard Shin & Instep Protection Guards",
        "Curved Leather Focus Punching Mitts Pair",
        "Full-Face Protection Leather Boxing Headgear",
        "Heavy Duty Speed Bag Swivel Assembly Kit",
        "Freestanding Heavy Punching Bag with Water Base",
        "Muay Thai Kick Pads (Pair)",
        "Professional Leather Sparring Gloves (16 oz)",
        "Tear-Resistant Canvas Heavy Bag (80 lbs)",
        "Gel-Enforced Inner Glove Hand Wraps",
        "Leather Thai Shin Guards with Hook & Loop Strap",
        "Target Kick Shield for Martial Arts Training",
        "Leather Speed Bag (Medium 9x6 Inch)",
        "Freestanding Reflex Boxing Bag with Spring Neck",
        "Muay Thai Pro Boxing Gloves (12 oz)",
        "Ergonomic Leather Focus Mitts Pair",
        "Pro Sparring Headgear with Removable Face Grill",
        "Double End Strike Bag with Bungee Cord Kit",
        "Heavy Leather Tear Drop Punching Bag (70 lbs)",
        "MMA Grappling Gloves (4 oz Competition Style)",
        "Semi-Elastic Boxing Hand Wraps (120-Inch)",
        "Leather Muay Thai Belly Pad Guard",
        "Pro Leather Boxing Bag (120 lbs / 5ft)",
        "Training Boxing Gloves (10 oz Lace-Up Style)",
        "Contoured Shin Guards for Kickboxing",
        "Curved Micro Punch Mitts for Precision",
        "Competition Boxing Headgear (Cheek Protection)",
        "Freestanding Heavy Bag with Multi-Zone Targets",
        "Heavy Canvas Wrecking Ball Punching Bag",
        "MMA Hybrid Training Gloves (7 oz)",
        "Mexican Style Cotton Hand Wraps (180-Inch)",
        "Heavy Duty Wall Mount Heavy Bag Hanger Bracket",
        "Pro Leather Focus Pads Pair",
        "Muay Thai Leather Shin Guards (Large)",
        "Full Face Leather Sparring Headgear",
        "Leather Speed Bag (Small 8x5 Inch)",
        "Water-Filled Heavy Punching Bag (120 lbs)",
        "Hook & Loop Training Boxing Gloves (16 oz)",
        "Heavy Duty Ceiling Mount Swivel Hanger",
        "Curved Thai Kick Pads (Pair)",
        "Grappling Dummy for BJJ & MMA Training (70 lbs)",
        "Gel Padded Boxing Hand Wraps Pair",
        "Leather Boxing Sparring Gloves (14 oz)",
        "Pro Muay Thai Belly & Rib Guard Protector",
        "Reflex Cobra Bag with Adjustable Height",
        "Canvas Heavy Punching Bag (60 lbs)",
        "Competition Shin & Instep Guards",
        "Leather Speed Bag with Dual Swivel",
        "Heavy Leather Angle Uppercut Punching Bag",
        "MMA Open-Palm Sparring Gloves (6 oz)",
        "Elasticized Boxing Hand Wraps (180-Inch)",
        "Freestanding Punching Tower with Water Base",
        "Pro Boxing Training Gloves (12 oz)",
        "Curved Leather Target Punch Mitts Pair",
        "Leather Headgear with Cheek & Chin Guard",
        "Muay Thai Strike Shield Target Pad",
        "Double-End Speed Bag Assembly",
        "Heavy Duty Steel Heavy Bag Wall Hanger",
        "Leather Boxing Training Gloves (16 oz)",
        "Gel Enforced Shin Guards for Martial Arts",
        "Tear Drop Leather Punching Bag (80 lbs)",
        "Hand Wraps Cotton Boxing Bandages Pair",
        "Pro Leather Focus Mitts for Trainer",
        "MMA Combat Sparring Gloves (5 oz)",
        "Competition Style Boxing Headgear",
        "Freestanding Reflex Boxing Punching Bag",
        "Heavy Leather Banana Bag (130 lbs / 6ft)",
        "Professional Lace-Up Boxing Gloves (14 oz)"
    ],
    "Recovery": [
        "High-Density Grid Foam Roller (18-Inch)",
        "Percussive Deep Tissue Massage Gun with 6 Heads",
        "Cold Plunge Cryotherapy Ice Bath Tub Container",
        "Gradient Athletic Leg Compression Sleeves Pair",
        "Recovery Epsom Salt Muscle Bath Soak (5 lbs)",
        "Electric Heated Muscle Massage Wrap Pad",
        "Vibrating Foam Roller for Deep Tissue Recovery",
        "Ergonomic Massage Ball for Trigger Point Release",
        "Pneumatic Air Compression Leg Recovery Boots",
        "Compact Deep Tissue Massage Gun (Quiet Brushless)",
        "Full Body Acupressure Mat & Pillow Set",
        "Infrared Thermal Heating Pad for Back & Joints",
        "Stainless Steel Scraping Muscle Gua Sha Tool Set",
        "Deep Tissue Dual Peanut Massage Ball",
        "Portable Cold Therapy Ice Bath Tub with Cover",
        "Percussive Massage Gun with OLED Touchscreen",
        "High-Density EVA Foam Roller (36-Inch Full Size)",
        "Targeted Calf & Foot Compression Sleeves",
        "Aromatherapy Epsom Salt Recovery Soak (3.5 lbs)",
        "Heat Therapy Electric Knee Massage Wrap",
        "Vibrating Massage Ball for Foot & Plantar Fasciitis",
        "Multi-Chamber Air Compression Leg Recovery System",
        "Mini Pocket Massage Gun for On-The-Go",
        "Ergonomic Contour Foam Roller (24-Inch)",
        "Stainless Steel Muscle Scraper Soft Tissue Tool",
        "Therapeutic Heating & Cooling Gel Ice Pack Wrap",
        "Deep Tissue Lacrosse Massage Ball Pair",
        "Inflatable Cold Therapy Ice Plunge Tub",
        "Professional Percussive Massage Gun (8 Speeds)",
        "Textured Hollow Grid Foam Roller (13-Inch)",
        "Graduated Arm Compression Sleeves Pair",
        "Pure Magnesium Chloride Muscle Recovery Spray",
        "Electric Heating Pad for Lower Back Pain Relief",
        "Acupressure Foot Massager Roller & Mat Set",
        "Air Compression Arm & Shoulder Recovery Sleeve",
        "Deep Tissue Trigger Point Massage Stick Roller",
        "High-Density Smooth EVA Foam Roller (18-Inch)",
        "Percussive Massage Gun with Heated Massage Head",
        "Cold Therapy Ice Recovery Wrap for Knees & Ankles",
        "Stainless Steel IASTM Muscle Scraping Tool",
        "Air Compression Calf & Foot Massager",
        "Pure Epsom Salt Muscle Recovery Soak (10 lbs)",
        "Electric Cordless Heated Neck & Shoulder Massager",
        "Soft Density Foam Roller for Gentle Muscle Release",
        "Double Peanut Muscle Massage Ball for Spine",
        "Portable Insulated Ice Bath Tub Container",
        "Pro Percussive Massage Gun with Metal Head Attachment",
        "Graduated Knee-High Compression Socks Pair",
        "Vibrating Deep Tissue Massage Peanut Ball",
        "Infrared Heating Pad with Jade & Tourmaline Stones",
        "Compact High-Density Roller (12-Inch)",
        "Targeted Plantar Fasciitis Foot Massage Roller",
        "Air Compression Leg Recovery Boots System",
        "Deep Muscle Massage Stick Roller with Handles",
        "Cold Plunge Tub Protection Cover & Pump Kit",
        "Professional Heavy-Duty Percussive Massager",
        "Spiky Trigger Point Massage Ball Set of 3",
        "Electric Heated Arm & Elbow Compression Wrap",
        "Magnesium Bath Flakes for Post-Workout Recovery",
        "High-Density Grid Foam Roller (30-Inch)",
        "Stainless Steel Muscle Scraping Tool (Type 2)",
        "Acupressure Back Stretcher & Lumbar Massage Board",
        "Mini Percussive Massage Gun (USB-C Rechargeable)",
        "Cold Therapy Ankle & Foot Ice Gel Boot",
        "Full Body Pneumatic Compression Massager",
        "Ergonomic Textured Foam Roller (14-Inch)",
        "Deep Tissue Muscle Massage Ball (Solid Rubber)",
        "Electric Infrared Heating Waist & Back Belt",
        "Epsom Salt Recovery Bath Soak with Eucalyptus",
        "Pro Air Compression Leg & Thigh Recovery Boots"
    ],
    "Accessories": [
        "Heavy-Duty Resistance Loop Bands Set (5 Resistance Levels)",
        "Genuine Grain Leather Powerlifting Belt (10mm Thickness)",
        "Elasticated Heavy-Duty Wrist Wraps (18-Inch Pair)",
        "Magnesium Carbonate Pure Gym Chalk Block (8-Pack)",
        "Speed Cable Jump Rope with Ball Bearings & Spare Cable",
        "Tactical Gym Duffel Bag with Shoe & Wet Compartment",
        "Padded Weightlifting Straps Pair (Heavy Cotton)",
        "Fabric Resistance Hip Circle Booty Bands (Set of 3)",
        "Heavy-Duty Lifting Hooks Grip Straps Pair",
        "Stainless Steel Vacuum Insulated Gym Shaker Bottle (24oz)",
        "Thick Bar Grips for Dumbbells & Barbells (Pair)",
        "Neoprene Dip Belt with Heavy Duty Steel Chain",
        "Weighted Jump Rope with Removable Handle Weights",
        "Gym Chalk Powder Ball in Reusable Mesh Bag",
        "Leather Weightlifting Gloves with Wrist Support",
        "Non-Slip Fabric Resistance Loop Band Set",
        "Prong Steel Buckle Leather Lifting Belt (13mm)",
        "Heavy Cotton Wrist Wraps with Thumb Loop (24-Inch)",
        "Large Capacity Gym Duffel Bag with Water Bottle Holder",
        "Self-Locking Nylon Weightlifting Belt (4-Inch)",
        "High-Speed Aluminum Handle Jump Rope",
        "Tritan BPA-Free Leakproof Protein Shaker Bottle (28oz)",
        "Silicone Padded Gym Workout Gloves Pair",
        "Long Pull-Up Assist Resistance Bands Set",
        "Figure 8 Weightlifting Straps Pair",
        "Liquid Gym Chalk Bottle (250ml Fast-Drying)",
        "Weighted Fitness Jump Rope (1 lb Heavy Cable)",
        "Convertible Gym Backpack & Duffel Bag",
        "Neoprene Knee Sleeves 7mm Pair for Squats",
        "Genuine Leather Contour Weightlifting Belt",
        "Elastic Ankle Straps for Cable Machine Attachment",
        "Heavy Duty Chalk Block 4-Pack Box",
        "Adjustable Leather Lifting Belt with Quick Release Lever",
        "Pro Speed Jump Rope with Anti-Slip Handles",
        "Stainless Steel Shaker Cup with Wire Mixer Ball",
        "Padded Gym Lifting Straps with Neoprene Support",
        "Fabric Resistance Loop Bands Pack of 4",
        "Tactical Molle Gym Backpack Bag (45L)",
        "Neoprene Elbow Sleeves 5mm Pair",
        "Pure Magnesium Carbonate Chalk Bowl Bag",
        "Lever Lock Leather Powerlifting Belt (10mm)",
        "Heavy Duty Cable Attachment Tricep Rope",
        "Speed Cable Jump Rope with Ergonomic Grips",
        "Insulated Stainless Steel Water Bottle (32oz)",
        "Weightlifting Wrist Wraps Pair (18-Inch Heavy Flex)",
        "Fabric Booty Bands Set for Glute Workouts",
        "Gym Chalk Block Single Pack",
        "Quick Release Lever Buckle Lifting Belt (13mm)",
        "Heavy Cotton Figure 8 Lifting Straps Pair",
        "Compact Gym Sports Duffle Bag",
        "Neoprene Padded Ankle Straps Pair for Cable Kickbacks",
        "High Speed Bearing Jump Rope with Steel Wire",
        "BPA-Free Shaker Bottle with Storage Compartments",
        "Genuine Leather Workout Gloves with Wrist Wraps",
        "Pull-Up Assistance Rubber Resistance Bands Set",
        "Professional Lever Powerlifting Belt (Custom Fit)",
        "Heavy Duty Chalk Ball in Drawstring Bag",
        "Spacious Gym Travel Duffel Bag with Shoe Pocket",
        "Neoprene Weightlifting Knee Sleeves 7mm Pair",
        "Quick-Lock Nylon Lifting Belt for Cross Training",
        "Heavy Duty Steel Dip Belt with Chain Assembly",
        "Pro Aluminum Handle Speed Jump Rope",
        "Insulated Vacuum Gym Water Bottle (40oz)",
        "Heavy Cotton Padded Weightlifting Straps",
        "Latex Free Fabric Resistance Loop Bands",
        "Liquid Gym Chalk Tube (100ml)",
        "Prong Buckle Leather Powerlifting Belt (10mm)",
        "Elasticated Heavy Wrist Wraps Pair (20-Inch)",
        "Compact Workout Gym Duffel Bag",
        "Heavy Duty Cable Attachment Handles Pair"
    ],
    "Apparel": [
        "Sweat-Wicking Performance Training Tee",
        "High-Waisted Compression Workout Shorts (5-Inch)",
        "Heavyweight Fleece Athletic Pullover Hoodie",
        "Leather Olympic Weightlifting Shoes with Raised Heel",
        "Tapered Sweat-Wicking Athletic Joggers",
        "Breathable Mesh Muscle Tank Top",
        "Seamless High-Support Gym Sports Bra",
        "Dry-Fit Compression Short Sleeve Shirt",
        "Technical Training Shorts with Liner (7-Inch)",
        "Lightweight Zip-Up Gym Track Jacket",
        "Ribbed Crop Top Workout Tank",
        "Thermal Compression Tights Pants",
        "Minimalist Cross-Training Athletic Shoes",
        "Oversized Cotton Heavy Weightlifting Tee",
        "High-Impact Zip Front Sports Bra",
        "Lightweight Running Shorts with Phone Pocket",
        "Fleece Lined Athletic Training Sweatpants",
        "Seamless Camo Workout Leggings",
        "Performance Quarter-Zip Running Pullover",
        "Breathable Mesh Inset Athletic Tank",
        "High-Performance Compression Base Layer Shirt",
        "Stretch Woven Training Shorts (9-Inch)",
        "Heavy Duty Leather Squat & Deadlift Shoes",
        "Classic Cotton Gym Graphic Tee",
        "Padded Medium Support Workout Sports Bra",
        "Ultra-Lightweight Track Running Pants",
        "Seamless High-Waisted Gym Leggings",
        "Oversized Heavyweight Gym Hoodie",
        "Dry-Fit Sleeveless Muscle Shirt",
        "Stretch Athletic Training Shorts (5-Inch)",
        "Thermal Base Layer Compression Leggings",
        "Technical Windbreaker Running Jacket",
        "Ribbed Seamless Crop Workout Top",
        "Tapered Fit Fleece Gym Joggers",
        "Breathable Mesh Back Performance Tee",
        "High-Support Cross-Back Sports Bra",
        "Barefoot Style Cross-Training Shoes",
        "Relaxed Fit Heavy Weightlifting Graphic Tee",
        "Compression Long Sleeve Rashguard Shirt",
        "High-Waisted Squat-Proof Workout Leggings",
        "Athletic Zip-Up Fleece Hoodie Jacket",
        "Lightweight 2-in-1 Running Shorts with Compression Liner",
        "Performance Muscle Tank Top with Drop Armholes",
        "Tapered Athletic Sweatpants with Zipper Pockets",
        "Dry-Fit Compression Short Sleeve Rashguard",
        "Seamless Ribbed Workout Leggings & Top Set",
        "High-Impact Padded Gym Sports Bra",
        "Heavy Duty Barefoot Lifting Shoes",
        "Oversized Drop-Shoulder Heavy Cotton Tee",
        "Lightweight Breathable Running Tank",
        "Thermal Compression Long Sleeve Top",
        "Stretch Woven Athletic Shorts (7-Inch)",
        "Fleece Athletic Hoodie with Kangaroo Pocket",
        "Tapered Cargo Gym Joggers with Zip Pockets",
        "High-Waisted Seamless Pocket Leggings",
        "Dry-Fit Short Sleeve Performance Training Shirt",
        "Low-Impact Strappy Yoga & Gym Sports Bra",
        "Minimalist Weightlifting Barefoot Shoes",
        "Breathable Mesh Muscle Cut Tank",
        "Compression Tights Shorts (6-Inch)",
        "Technical Quarter-Zip Training Top",
        "Oversized Vintage Washed Gym Tee",
        "High-Waisted Compression Leggings (7/8 Length)",
        "Lightweight Track Jacket with Mesh Lining",
        "Fleece Lined Athletic Training Hoodie",
        "Stretch Athletic Shorts with Built-In Liner",
        "Seamless Long Sleeve Crop Top",
        "Tapered Performance Gym Joggers",
        "Dry-Fit Sleeveless Training Hoodie",
        "Heavy Duty Leather Powerlifting Shoes"
    ],
    "Fit Tech": [
        "GPS Sports Smartwatch with Heart Rate Monitor",
        "Chest Strap Heart Rate Monitor Sensor (ANT+ & Bluetooth)",
        "Smart Body Fat & Composition Digital Scale",
        "Pneumatic Air Compression Leg Recovery Boots",
        "Continuous Pulse Oximeter & Oxygen Tracker",
        "Smart Fitness Tracker Ring with Sleep Analysis",
        "Bluetooth Heart Rate Armband Monitor",
        "HD Touchscreen Fitness Display Console",
        "Smart Muscle Stimulator TENS EMS Device",
        "Wearable GPS Multisport Watch with Map Navigation",
        "Bluetooth Smart Body Analyzer Scale",
        "Wireless Heart Rate Chest Strap Sensor",
        "Smart Jump Rope with LED Jump Counter",
        "Handheld Percussive Body Composition Analyzer",
        "Smart Workout Tracker Wristband with SpO2 Sensor",
        "Bluetooth Audio Sport Earbuds with Earhooks",
        "Smart Speedometer & Cadence Sensor for Bikes",
        "Wearable Thermal Muscle Warming Device",
        "Wireless Digital Grip Strength Dynamometer Tester",
        "GPS Running Smartwatch with Music Storage",
        "Chest Harness Heart Rate Sensor for Training",
        "Smart Digital Scale with Smartphone App Sync",
        "Pneumatic Compression Arm & Leg Boots System",
        "Smart Speed & Jump Counter Rope",
        "Bluetooth Fitness Tracker Wristband",
        "Smart TENS Unit Muscle Relief Controller",
        "Wireless Sports Earbuds with Active Noise Cancellation",
        "Smart Bike Computer with GPS Navigation",
        "Continuous Glucose & Workout Monitor Sensor",
        "GPS Multisport Watch with Sapphire Crystal Lens",
        "Dual-Band Heart Rate Chest Strap (Bluetooth/ANT+)",
        "Smart Wi-Fi Body Composition Glass Scale",
        "Air Compression Recovery Boots with Control Unit",
        "Smart Fitness Tracker Ring (Titanium Edition)",
        "Bluetooth Heart Rate Armband Monitor Sensor",
        "Wearable Electrostimulation EMS Abdominal Belt",
        "Wireless Open-Ear Bone Conduction Sport Headphones",
        "Smart Sensor Speedometer for Cycling",
        "Digital Hand Grip Dynamometer Tester (90kg / 200lbs)",
        "GPS Smartwatch with Solar Charging Lens",
        "Precision Heart Rate Monitor Chest Strap",
        "Smart Bluetooth Body Composition Analyzer Scale",
        "Wearable Pulse Oximeter Sleep & Workout Tracker",
        "Smart LED Counter Jump Rope",
        "Waterproof Fitness Tracker Wristband",
        "Wireless TENS EMS Muscle Massager Unit",
        "Bluetooth Sports Earphones with Sweat Resistance",
        "Smart GPS Cycling Computer Display",
        "Smart Fitness Ring with Temperature & Heart Rate Sensor",
        "Multisport GPS Watch with Barometric Altimeter",
        "Soft Fabric Heart Rate Chest Strap Sensor",
        "Smart Body Fat Scale with 8 Electrode Sensors",
        "Pneumatic Compression Recovery Pants System",
        "Smart Bluetooth Fitness Wristband",
        "Wearable EMS Muscle Toning Belt",
        "Open-Ear Bone Conduction Wireless Sport Headset",
        "Smart Cadence & Speed Sensor Pair for Bikes",
        "Digital Grip Strength Tester Meter",
        "Advanced GPS Multisport Smartwatch",
        "Bluetooth Heart Rate Monitor Strap",
        "Smart Wi-Fi Body Fat Composition Scale",
        "Air Compression Leg Massager Boots Device",
        "Smart Fitness Tracker Ring (Black Edition)",
        "Wireless Heart Rate Armband Monitor",
        "Portable TENS EMS Electronic Pulse Massager",
        "Waterproof Sport Earbuds with Secure Fit Hooks",
        "Smart Bike GPS Navigation Display",
        "Continuous Heart Rate & Activity Tracker Ring",
        "GPS Smartwatch with AMOLED Display",
        "Chest Strap Heart Rate Sensor Transmitter"
    ],
    "Supplements": [
        "100% Whey Protein Isolate Powder (Vanilla 5 lbs)",
        "High-Explosive Pre-Workout Powder (Sour Apple 30 Servings)",
        "Micronized Creatine Monohydrate Powder (500g Unflavored)",
        "Instantized BCAA 2:1:1 Energy Powder (Blue Raspberry 300g)",
        "Essential Athlete Daily Multivitamin Pack (60 Capsules)",
        "Advanced Clean Mass Gainer Powder (Chocolate 6 lbs)",
        "Pure Hydrolyzed Collagen Peptides Powder (450g)",
        "Electrolyte Hydration Powder Sticks (Lemon Lime 30 Packs)",
        "Plant-Based Vegan Organic Protein Powder (Chocolate 2 lbs)",
        "Nighttime Micellar Casein Protein Powder (Chocolate 4 lbs)",
        "Nitric Oxide Pump Pre-Workout Booster (Fruit Punch)",
        "Creapure Micronized Creatine Powder (250g)",
        "Fermented Essential Amino Acids EAA Powder (Watermelon)",
        "High-Potency Omega-3 Fish Oil Softgels (120 Softgels)",
        "Extreme Mass Gainer Powder (Vanilla 10 lbs)",
        "Hydrolyzed Whey Isolate Protein (Strawberry 4 lbs)",
        "Stimulant-Free Pump Pre-Workout Powder (Unflavored)",
        "Micronized Creatine Monohydrate Powder (1kg Bulk)",
        "BCAA Intra-Workout Powder with Electrolytes (Mango 400g)",
        "Athlete Joint Support Complex Capsules (90 Capsules)",
        "Organic Plant Protein Powder (Vanilla Bean 2 lbs)",
        "Slow-Digesting Micellar Casein Powder (Vanilla 4 lbs)",
        "High Energy Pre-Workout Formula (Watermelon 30 Servings)",
        "Pure Creatine Monohydrate Capsules (250 Capsules)",
        "EAA + Electrolyte Recovery Powder (Fruit Punch 30 Servings)",
        "Daily Greens & Superfood Powder Blend (300g)",
        "High Calorie Lean Mass Gainer (Cookies & Cream 5 lbs)",
        "100% Whey Isolate Protein Powder (Chocolate Fudge 5 lbs)",
        "Non-Stim Pre-Workout Pump Matrix (300g)",
        "Micronized Creatine Monohydrate Powder (300g)",
        "BCAA Energy Powder Drink Mix (Grape 30 Servings)",
        "ZMA Nighttime Recovery Capsules (90 Capsules)",
        "Plant Protein Isolate Powder (Unflavored 2 lbs)",
        "Micellar Casein Protein Powder (Salted Caramel 2 lbs)",
        "Advanced Pre-Workout Powder Formula (Blue Raspberry)",
        "Micronized Creatine Monohydrate Capsules (120 Capsules)",
        "Essential Amino Acid EAA Energy Powder (Peach Mango)",
        "High-Potency Vitamin D3 + K2 Softgels (120 Softgels)",
        "High Calorie Mass Gainer Powder (Chocolate Peanut Butter 6 lbs)",
        "Hydrolyzed Whey Protein Isolate (Cookies & Cream 5 lbs)",
        "High-Stim Pre-Workout Energy Powder (Green Apple)",
        "Pure Micronized Creatine Powder (500g Tub)",
        "BCAA 2:1:1 Intra-Workout Powder (Lemonade 30 Servings)",
        "Daily Multivitamin for Men & Women (120 Tablets)",
        "Organic Vegan Plant Protein Powder (Chocolate Silk 2.5 lbs)",
        "Nighttime Casein Protein Powder (Vanilla Cream 4 lbs)",
        "Nitric Oxide Pre-Workout Powder (Tropical Punch)",
        "Creatine Monohydrate Powder (200 Mesh Ultra-Fine 500g)",
        "EAA Hydration Recovery Powder (Watermelon Ice 30 Servings)",
        "Hydrolyzed Collagen Peptides Unflavored Powder (500g)",
        "Lean Mass Gainer Protein Powder (Vanilla Shake 5 lbs)",
        "100% Whey Protein Isolate (Rich Chocolate 5 lbs)",
        "Stim-Free Pre-Workout Pump Formula (30 Servings)",
        "Pure Micronized Creatine Monohydrate (250g)",
        "BCAA Energy Intra-Workout Powder (Cherry Limeade)",
        "High-Yield Fish Oil Omega-3 Softgels (180 Count)",
        "Plant Based Pea & Rice Protein Powder (Vanilla 2 lbs)",
        "Slow Release Casein Protein Powder (Chocolate 5 lbs)",
        "Pre-Workout Energy & Focus Powder (Sour Gummy)",
        "Micronized Creatine Monohydrate Powder (500g Unflavored)",
        "EAA + BCAAs Amino Recovery Powder (Fruit Punch)",
        "Daily Athlete Multivitamin Tablets (90 Count)",
        "High Calorie Mass Gainer Protein (Chocolate 10 lbs)",
        "Hydrolyzed Whey Isolate Powder (Vanilla 5 lbs)",
        "Pre-Workout Nitric Oxide Booster (Unflavored Powder)",
        "Pure Creatine Monohydrate Powder (1000g Bulk)",
        "BCAA 2:1:1 Recovery Powder (Blue Raspberry 30 Servings)",
        "Superfood Greens & Berry Antioxidant Powder (300g)",
        "Organic Plant Protein Powder (Salted Caramel 2 lbs)",
        "Micellar Casein Nighttime Protein (Chocolate Milk 4 lbs)"
    ],
    "Yoga": [
        "Eco-Friendly Non-Slip Alignment Yoga Mat (6mm)",
        "High-Density EVA Foam Yoga Blocks (Set of 2)",
        "Durable Cotton Yoga Stretching Strap (8 Feet)",
        "Organic Cotton Meditation Bolster Pillow",
        "Textured Cork Yoga Wheel for Back Extension",
        "Lightweight Yoga Mat Carrying Sling Strap",
        "Premium Natural Rubber Yoga Mat (5mm)",
        "High-Density Cork Yoga Blocks Pair",
        "Adjustable Metal Buckle Yoga Strap (10 Feet)",
        "Round Cotton Meditation Cushion (Zafu)",
        "Deep Tissue Muscle Yoga Wheel (12-Inch)",
        "Absorbent Microfiber Yoga Mat Towel",
        "Extra Thick Cushioning Yoga Mat (8mm)",
        "Recycled EVA Foam Yoga Block Pair",
        "Cotton Yoga Stretching Belt Strap (6 Feet)",
        "Rectangular Yoga Bolster Pillow Cushion",
        "Wood Grain Yoga Wheel Back Stretcher",
        "Waterproof Canvas Yoga Mat Bag with Pockets",
        "Non-Slip PU Leather Yoga Mat (4.5mm)",
        "Natural Eco Cork Yoga Block Pair",
        "Heavy Duty Cotton Yoga Strap with D-Ring",
        "Buckwheat Meditation Cushion Pillow",
        "Spine Release Yoga Wheel (10-Inch)",
        "Non-Slip Microfiber Yoga Towel with Grip Dots",
        "Extra Wide TPE Yoga Mat (6mm)",
        "High Density Foam Yoga Block Set with Strap",
        "Multi-Loop Stretching Yoga Belt Strap",
        "Organic Cotton Round Yoga Bolster",
        "Textured Rubber Yoga Wheel Stretcher",
        "Full Zip Canvas Yoga Mat Tote Bag",
        "Alignment Line Non-Slip Yoga Mat (5mm)",
        "Lightweight Travel EVA Foam Yoga Block",
        "Cotton Yoga Strap with Metal D-Ring (8ft)",
        "Rectangular Meditation Pillow Cushion",
        "Back Release Roller Yoga Wheel (13-Inch)",
        "Sweat Absorbent Yoga Mat Towel Full Size",
        "Premium Natural Rubber Yoga Mat (6mm)",
        "High Density Cork Yoga Block Single",
        "Yoga Stretching Strap with Loop Handles",
        "Soft Velvet Meditation Bolster Cushion",
        "Ergonomic Yoga Wheel Stretcher Device",
        "Canvas Yoga Mat Backpack Bag",
        "Non-Slip Travel Foldable Yoga Mat (1.5mm)",
        "High Density EVA Foam Yoga Block Pair (4-Inch)",
        "Adjustable Cotton Yoga Belt Strap (8 Feet)",
        "Buckwheat Meditation Zafu Pillow Cushion",
        "Spine Massager Yoga Wheel Roller",
        "Non-Slip Yoga Towel with Corner Pockets",
        "Extra Thick Comfort Yoga Mat (10mm)",
        "Eco Friendly Cork Yoga Block Pair",
        "Heavy Duty Stretching Strap for Flexibility",
        "Organic Cotton Yoga Bolster Pillow (Large)",
        "Deep Back Stretcher Yoga Wheel (12-Inch)",
        "Water Resistant Yoga Mat Bag Sleeve",
        "Alignment Marker Non-Slip Yoga Mat (6mm)",
        "High Density Foam Yoga Block Pair (3-Inch)",
        "Multi Grip Yoga Stretching Strap",
        "Round Velvet Meditation Cushion",
        "Textured Spine Release Yoga Wheel",
        "Full Length Microfiber Yoga Towel",
        "Natural Rubber Pro Yoga Mat (5mm)",
        "Premium Cork Yoga Block Set",
        "Cotton Yoga Stretching Strap (10 Feet)",
        "Rectangular Yoga Bolster Pillow",
        "Ergonomic Yoga Wheel Back Roller",
        "Canvas Yoga Mat Carrying Shoulder Bag",
        "Eco TPE Non-Slip Yoga Mat (6mm)",
        "High Density EVA Foam Yoga Block",
        "Adjustable Metal Buckle Yoga Strap (8ft)",
        "Organic Cotton Meditation Bolster Pillow"
    ],
    "Home Gym": [
        "Quick-Select Adjustable Dumbbells Pair (5-52.5 lbs)",
        "Space-Saving Foldable Utility Weight Bench",
        "Doorway Multi-Grip Pull-Up Bar Station",
        "Suspension Bodyweight Trainer Straps Kit",
        "Multi-Station Heavy Duty Power Tower",
        "Interlocking High-Density Rubber Gym Floor Tiles (6-Pack)",
        "Adjustable Dumbbells Set with Stand (5-70 lbs)",
        "Heavy Duty Wall-Mounted Pull-Up Bar",
        "Suspension Trainer Pro Kit with Door Anchor",
        "Power Tower Dip Station with Captains Chair",
        "Heavy Duty Interlocking Rubber Gym Matting (1/2 Inch)",
        "Compact Foldable Incline Weight Bench",
        "Doorway Chin-Up & Pull-Up Bar",
        "Bodyweight Suspension Strap System with Anchor",
        "Multi-Grip Power Tower Dip Station",
        "High-Density Rubber Gym Flooring Mats (4-Pack)",
        "Dial Adjustable Dumbbells Pair (10-90 lbs)",
        "Heavy Duty Foldable Flat Weight Bench",
        "Wall Mounted Multi-Grip Chin-Up Bar",
        "Commercial Suspension Bodyweight Trainer Kit",
        "Heavy Duty Power Tower Pull-Up Dip Station",
        "Interlocking Rubber Gym Floor Tiles (12-Pack)",
        "Quick-Change Adjustable Dumbbells Pair (5-25 lbs)",
        "Foldable Slope Utility Bench for Home Gym",
        "Doorway Pull-Up Bar with Padded Handles",
        "Professional Suspension Trainer Straps System",
        "Multi-Grip Pull-Up Dip Power Tower Station",
        "High Density Rubber Gym Flooring Tile (single)",
        "Adjustable Dial Dumbbell Set with Tray (5-50 lbs)",
        "Compact Folding Weight Bench Press",
        "Ceiling Mounted Steel Pull-Up Bar Station",
        "Bodyweight Suspension Trainer with Door Mount",
        "Heavy Duty Power Tower Station with Push-Up Handles",
        "Interlocking Foam & Rubber Gym Mats (8-Pack)",
        "Quick-Select Dumbbell Pair (10-55 lbs)",
        "Foldable Adjustable FID Weight Bench",
        "Heavy Duty Doorway Chin Up Pull Up Bar",
        "Professional Bodyweight Suspension Trainer Kit",
        "Power Tower Pull Up Dip Station with Padded Armrests",
        "High Density Rubber Gym Mat Roll (4ft x 10ft)",
        "Adjustable Weight Dumbbells Set (5-52.5 lbs Pair)",
        "Space-Saving Foldable Incline Decline Bench",
        "Wall-Mounted Heavy Steel Pull-Up Bar",
        "Suspension Trainer System with Extension Strap",
        "Multi-Station Power Tower Dip Pull-Up Station",
        "Heavy Duty Interlocking Gym Floor Tiles (16-Pack)",
        "Quick Select Dial Dumbbells Set (5-70 lbs)",
        "Compact Foldable Flat Utility Bench",
        "Doorway Multi-Grip Pull-Up Bar No-Screws Mount",
        "Bodyweight Suspension Fitness Trainer Kit",
        "Heavy Duty Power Tower Station for Home Gym",
        "Interlocking Rubber Gym Matting Tiles (24-Pack)",
        "Adjustable Dumbbells Pair with Custom Rack (5-50 lbs)",
        "Foldable Multi-Position Weight Bench",
        "Heavy Duty Ceiling Mount Pull-Up Bar",
        "Commercial Suspension Trainer System",
        "Multi-Grip Power Tower Dip Pull-Up Station",
        "High Density Rubber Gym Flooring Mat (1/4 Inch)",
        "Quick-Select Adjustable Dumbbells Pair (10-40 lbs)",
        "Space-Saving Foldable Utility Weight Bench",
        "Doorway Chin-Up Bar with Safety Lock",
        "Suspension Bodyweight Fitness Trainer Kit",
        "Power Tower Dip Station Pull-Up Machine",
        "Interlocking High-Density Rubber Gym Tiles (8-Pack)",
        "Adjustable Dial Dumbbell Pair (5-52.5 lbs)",
        "Compact Foldable Incline Weight Bench",
        "Wall-Mounted Steel Pull-Up Bar System",
        "Bodyweight Suspension Trainer Straps Set",
        "Heavy Duty Power Tower Station (1000lb Limit)",
        "Interlocking Rubber Gym Floor Mat Roll"
    ]
}

# Read existing products
with open('products.js', 'r', encoding='utf-8') as f:
    raw_js = f.read()

json_str = raw_js[raw_js.find('['):raw_js.rfind(']')+1]
products = json.loads(json_str)

# Group products by category and assign unique names
category_counters = {cat: 0 for cat in categories_names}
all_assigned_names = set()

for p in products:
    cat = p['category']
    idx = category_counters[cat]
    name_candidate = categories_names[cat][idx]
    
    # Ensure name uniqueness across the entire website
    if name_candidate in all_assigned_names:
        name_candidate = f"{name_candidate} (v{idx+1})"
    
    p['name'] = name_candidate
    all_assigned_names.add(name_candidate)
    category_counters[cat] += 1

print(f"Total products updated: {len(products)}")
print(f"Total unique names: {len(all_assigned_names)}")

# Write updated products.js
js_content = f"const shopProducts = {json.dumps(products, indent=4)};"
with open('products.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print("Successfully updated products.js with 700 unique, realistic product names!")

# Also generate product_listing.md
md_lines = ["# FitVerse Product Listing\n", f"Total Products: **{len(products)}**\n", "## Category Summary\n", "| Category | Number of Products |", "| --- | --- |"]
for cat in categories_names:
    md_lines.append(f"| {cat} | 70 |")

md_lines.append("\n---\n")

for cat in categories_names:
    md_lines.append(f"\n## Category: {cat} (70 products)\n")
    md_lines.append("| Product ID | Product Name |")
    md_lines.append("| --- | --- |")
    cat_prods = [p for p in products if p['category'] == cat]
    for p in cat_prods:
        md_lines.append(f"| {p['id']} | {p['name']} |")

with open('product_listing.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(md_lines))

print("Successfully updated product_listing.md!")
